apiVersion: apps/v1
kind: Deployment
metadata:
 name: nexus-dep
 namespace: devops
spec:
 replicas: 1
 selector:
  matchLabels:
   app: nexus-server
 template:
  metadata:
   labels:
    app: nexus-server
  spec:
   containers:
   - name: nexus
     image: sonatype/nexus3:3.25.0
     resources: 
      requests:
       cpu: "500m"
       memory: "1Gi"
      limits:
       cpu: "1000m"
       memory: "2Gi"
     volumeMounts:
     - name: nexus-data
       mountPath: /nexus-data
   volumes:
   - name: nexus-data
     persistentVolumeClaim:
      claimName: pvc-nfs
 
