apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nexus-dep
  namespace: devops-nexus
spec:
  serviceName: nexus-service
  replicas: 1
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
    containers:
      - name: nexus
        image: sonatype/nexus3:3.29.0
        resources: 
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "800Mi"
        volumeMounts:
          - name: nexus-data
            mountPath: /nexus-data
#    volumes:
#      - name: nexus-data
#        persistentVolumeClaim:
#          claimName: nexus-pvc-nfs
    volumeClaimTemplates:
    - metadata:
      name: pvc-nexus
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: nfs-sc
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: devops-nexus
spec:
  selector:
    app: nexus-server
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 32000