apiVersion: v1
kind: Service
metadata:
  name: nexus-svc
  namespace: devops
spec:
  selector:
    app: nexus-server
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 32000