apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana-nodeport
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: prometheus-port
    port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 32091
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana