apiVersion: v1
kind: Service
metadata:
  name: prometheus-operated-nodeport
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: grafana-port
    port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 32090
  selector:
    app: prometheus