# storage class scope is outside the scope
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storageclass # IMPORTANT pvc needs to mention this name
provisioner: nfs-dynamic-provisioner # name can be anything
parameters:
  archiveOnDelete: "false"
