# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
ENV['VAGRANT_EXPERIMENTAL'] = 'disks'

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu-01" do |vm1|
    vm1.vm.hostname = "ubuntu-01"
    vm1.vm.box = "generic/ubuntu1804"
    vm1.vm.box_check_update = false
    vm1.vm.network "private_network", ip: "192.168.10.100"
    vm1.vm.network "public_network"
    vm1.vm.disk :disk, size: "20GB", primary: true
  
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-01"
      vb.gui = false  
      vb.memory = "2048"
      vb.cpus = "2"
    end

    vm1.vm.provision "shell", inline: <<-SHELL
      #apt-get update
      ifconfig
    SHELL
  end
end