ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
ENV['VAGRANT_EXPERIMENTAL'] = 'disks'
# IMAGE_NAME = "bento/ubuntu-18.04"
# IMAGE_NAME = "bento/ubuntu-16.04"
# IMAGE_NAME = "generic/ubuntu1804"
IMAGE_NAME = "bento/ubuntu-20.04"
MASTER_COUNT = 1
NODE_COUNT = 1
IP_NETWORK = "192.168.10."

Vagrant.configure("2") do |config|
  #config.ssh.insert_key = false

  (1..MASTER_COUNT).each do |i|
    config.vm.define "master-0#{i}" do |master|
      master.vm.hostname = "master-0#{i}"
      master.vm.box = IMAGE_NAME
      master.vm.box_check_update = false
      master.vm.network "private_network", ip: "#{IP_NETWORK}#{i+10}"
      master.vm.network "forwarded_port", guest: 22, host: "#{2710 + i}"
      master.vm.provision "setup-dns", type: "shell", :path => "ubuntu/update-dns.sh"
      master.vm.network "public_network"
      master.vm.provider "virtualbox" do |vbMaster|
        vbMaster.name = "master-0#{i}"
        vbMaster.gui = false
        vbMaster.memory = "2048"
        vbMaster.cpus = "2"
      end
      #master.vm.provision "ansible" do |ansible|
      #  ansible.playbook = "ansible-kubernetes/playbook-common.yaml"
      #  ansible.extra_vars = {
      #      node_ip: "192.168.10.10",
      #  }
      #end
    end
  end

  (1..NODE_COUNT).each do |j|
    config.vm.define "node-0#{j}" do |node|
      node.vm.hostname = "node-0#{j}"
      node.vm.box = IMAGE_NAME
      node.vm.network "private_network", ip: "#{IP_NETWORK}#{j+20}"
      node.vm.network "forwarded_port", guest: 22, host: "#{2720  + j}"
      node.vm.provision "setup-dns", type: "shell", :path => "ubuntu/update-dns.sh"
      node.vm.network "public_network"
      node.vm.provider "virtualbox" do |vbWorker|
        vbWorker.name = "node-0#{j}"
        vbWorker.gui = false
        vbWorker.memory = "4096" #4096
        vbWorker.cpus = "2"
      end
      #node.vm.disk :disk, size: "20GB", primary: true
      #node.vm.provision "ansible" do |ansible|
      #  ansible.playbook = "ansible-kubernetes/node-playbook.yml"
      #  ansible.extra_vars = {
      #      node_ip: "192.168.10.#{i + 10}",
      #  }
      #end
    end
  end
end