apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: devops
spec:
  selector:
    app: jenkins-server
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32010