---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: devops-sonarqube
spec:
  selector:
    app: nexus
  type: ClusterIP
  ports:
    - name: http
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-dep
  namespace: devops-sonarqube
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.6
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: SONARQUBE_POSTGRES_DB
          value: sonarqube
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: SONARQUBE_POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: SONARQUBE_POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres
    volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: pvc-postgres