apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dep
  namespace: devops-sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.6
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
          name: postgres-config
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: pvc-postgres