kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-postgres
  namespace: devops-sonarqube
spec:
  storageClassName: nfs-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi