apiVersion: v1
kind: Service
metadata:
  name: sonarqube-svc
  namespace: devops
spec:
  selector:
    app: sonarqube
  type: NodePort
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    nodePort: 32040