apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-dep
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:7.9.5-community
        env:
        - name: SONARQUBE_JDBC_URL
          value: "jdbc:postgresql://sonarqube-postgres-svc:5432/sonardb"
        - name: SONARQUBE_JDBC_USERNAME
          valueFrom:
            secretKeyRef:
              name: sonarqube-postgres-secret
              key: SONARQUBE_POSTGRES_USER
        - name: SONARQUBE_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarqube-postgres-secret
              key: SONARQUBE_POSTGRES_PASSWORD
        resources: 
          requests:
            cpu: "500m"
            memory: "1000Mi"
          limits:
            cpu: "1000m"
            memory: "2000Mi"
        readinessProbe:
          httpGet:
            path: /about
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /about
            port: 9000
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 6
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: "/opt/sonarqube/data/"
          name: sonar-data
        - mountPath: "/opt/sonarqube/extensions/"
          name: sonar-extensions
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
          claimName: sonarqube-data-pvc
      - name: sonar-extensions
        persistentVolumeClaim:
          claimName: sonarqube-extensions-pvc