apiVersion: v1
kind: Service
metadata:
  name: sonarqube-postgres-svc
  namespace: devops
spec:
  selector:
    app: sonarqube-postgres
  type: ClusterIP
  ports:
  - name: http
    port: 5432
    targetPort: 5432