apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
  namespace: devops
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
      nodePort: 32021
    - name: http
      port: 80
      targetPort: http
      nodePort: 32020