apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab-postgres-sts
  namespace: devops
spec:
  serviceName: gitlab-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-postgres
  template:
    metadata:
      labels:
        app: gitlab-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.6
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: gitlab-postgres-configmap
              key: GITLAB_POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: gitlab-postgres-secret
              key: GITLAB_POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-postgres-secret
              key: GITLAB_POSTGRES_PASSWORD
        ports:
        - name: gitlab-postgres 
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: gitlab-postgres
      volumes:
      - name: gitlab-postgres
        persistentVolumeClaim:
          claimName: gitlab-postgres-pvc