apiVersion: v1
kind: Service
metadata:
  name: gitlab-postgres-svc
  namespace: devops
spec:
  selector:
    app: gitlab-postgres
  ports:
    - name: postgres-gitlab
      port: 5432
      targetPort: postgres-gitlab