apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-nfs
spec:
 storageClassName: nfs
 volumeMode: Filesystem
 capacity:
  storage: 5Gi
 accessModes:
  - ReadWriteMany
 nfs:
  server: 192.168.56.102
  path: /mnt/nfs-share
