---
- hosts: all
  vars:
    master_node_ip: 192.168.10.11
    pod_network_cidr: 192.168.50.0/24
  become: true
  tasks:
  - name: Add a line to a file if the file does not exist, without passing regexp
    ansible.builtin.lineinfile:
      path: /etc/resolv.conf
      line: nameserver 8.8.8.8