---
- hosts: all
  become: true
  tasks:
  - name: Update packages
    command: "{{ item }}"
    with_items:
    - sudo rm -vf /var/lib/apt/lists/*
    - sudo apt-get update

  - name: Install Packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
      - nfs-common

  - name: Disable swap space
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Add apt signing key for docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      
  - name: Add apt reposiotry for docker
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

  - name: Update packages
    command: "{{ item }}"
    with_items:
    - sudo apt-get update
      
  - name: Install docker
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    notify:
      - docker status

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker
