---
- hosts: all
  become: true
  tasks:
  - name: Install Packages
    apt:
      state: latest
      update_cache: yes
      pkg:
      - apt-transport-https
      - curl
      - nfs-common

  - name: Disable swap space
    command: swapoff -a
    when: ansible_swaptotal_mb > 0