---
- hosts: all
  become: true
  tasks:
  - name: Install Packages
    apt:
      name: "{{packages}}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - curl
      - nfs-common
