---
- hosts: all
  vars:
    node_ip: 192.168.10.10
  become: true
  tasks:
  - name: Update packages
    command: "{{ item }}"
    with_items:
    - rm -vf /var/lib/apt/lists/*
    - apt-get update

  - name: Install Packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
      - nfs-common

  - name: Disable swap space
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Docker apt signing key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      
  - name: Docker apt reposiotry
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

  - name: Update packages
    command: "{{ item }}"
    with_items:
    - apt-get update
      
  - name: Install docker
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    notify:
      - docker status

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  - name: Kubernetes apt signing key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Kubernetes apt repository
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl