---
- hosts: all
  vars:
    master_node_ip: 192.168.10.11
    pod_network_cidr: 192.168.50.0/24
  become: true
  tasks:
  - name: Update /etc/resolv.conf for corporate network
    ansible.builtin.lineinfile:
      path: /etc/resolv.conf
      line: nameserver 8.8.8.8

  - name: Update packages
    command: "{{ item }}"
    with_items:
    #- sudo rm -vf /var/lib/apt/lists/*
    - sudo apt update

  - name: Install Packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
      - nfs-common

  - name: Disable swap space
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Find distribution
    command: lsb_release -sc
    register: result

  - name: Docker apt signing key and apt repository
    #apt_key:
    #  url: https://download.docker.com/linux/ubuntu/gpg
    command: "{{ item }}"
    with_items:
    - sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key --keyring /etc/apt/trusted.gpg.d/docker.gpg add -
    #- sudo add-apt-repository deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable
    #- sudo apt update
    retries: 3
