---
- hosts: all
  vars:
    master_node_ip: 192.168.10.11
    pod_network_cidr: 192.168.50.0/24
  become: true
  tasks:
  
  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="{{ master_node_ip }}" --apiserver-cert-extra-sans="{{ master_node_ip }}"  --node-name k8s-master --pod-network-cidr={{ pod_network_cidr }}

  - name: Setup kubeconfig for vagrant user
    shell: |
      mkdir -p /home/vagrant/.kube
      cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
      chown vagrant:vagrant /home/vagrant/.kube/config

  - name: Install calico pod network
    become: false
    command: kubectl apply -f calico.yaml

  - name: Install dashboard
    become: false
    command: |
      - kubectl apply -f dashboard.yaml
      - kubectl apply -f dashboard-admin.yaml
      - kubectl apply -f dashboard-read-only.yaml