---
- hosts: worker-node
  vars:
    MASTER_IP: 192.168.10.11
    NON_ROOT_USER: vagrant
    DATA_PATH: /opt/kubernetes/
  become: true
  tasks:

  - name: Get join command from master
    copy: src=shared-data-command dest=/tmp/shared-data.sh mode=0777

  - name: Join node to cluster
    command: sh /tmp/shared-data.sh

  - name: 1 minute wait for initialization
    pause:
      minutes: 1

  - name: Copy admin.conf from local host to remote
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: '/tmp/admin.conf', dest: /etc/kubernetes/admin.conf }

  - name: Configure for non-root user
    shell: |
      sudo rm -rf $HOME/.kube
      mkdir -p $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config
    become: yes
    become_user: "{{ NON_ROOT_USER }}"

  - name: Configure for root user
    shell: |
      sudo rm -rf $HOME/.kube
      mkdir -p $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Auto completion for non-root user
    shell: |
      echo "source <(kubectl completion bash)" >>~/.bashrc
    become_user: "{{ NON_ROOT_USER }}"

  - name: Auto completion for root user
    shell: |
      echo "source <(kubectl completion bash)" >>~/.bashrc
      sudo kubectl completion bash >/etc/bash_completion.d/kubectl

  - name: Setup auto completion
    shell: |
      source $HOME/.bashrc && source /usr/share/bash-completion/bash_completion
    args:
      executable: /bin/bash

  # Following step is to resolve logs/exec error on worker node
  - name: Grant NFS Share Access to Client Systems
    ansible.builtin.lineinfile:
      path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      line: 'Environment="KUBELET_EXTRA_ARGS=--node-ip=192.168.10.21"'
      create: yes

  - name: Restart kubelet
    shell: |
      systemctl daemon-reload
      systemctl restart kubelet

  - name: Copy yaml files
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: 'ingress-nginx.yaml', dest: "{{ DATA_PATH }}" }

  - name: Install nginxingress
    shell:
        kubectl apply
        -f "{{ DATA_PATH }}"ingress-nginx.yaml

  - name: 2 minute wait for initialization
    pause:
      minutes: 2