---
- hosts: master-node
  vars:
    MASTER_IP: 192.168.10.11
    POD_CIDR: 192.168.50.0/24
    DATA_PATH: /opt/kubernetes/
  become: true
  tasks:
  
#  - name: Initialize the Kubernetes cluster using kubeadm
#    command: kubeadm init --apiserver-advertise-address="{{ MASTER_IP }}" --apiserver-cert-extra-sans="{{ MASTER_IP }}"  --node-name k8s-master --pod-network-cidr={{ POD_CIDR }}

  - name: Initialize kubectl command
    shell: |
      sudo rm -rf $HOME/.kube
      mkdir -p $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config
    become: yes
    become_user: vagrant

  - name: Copy yaml files
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: 'calico.yaml', dest: "{{ DATA_PATH }}" }
      - { src: 'dashboard.yaml', dest: "{{ DATA_PATH }}" }
      - { src: 'dashboard-admin.yaml', dest: "{{ DATA_PATH }}" }
      - { src: 'dashboard-read-only.yaml', dest: "{{ DATA_PATH }}" }

  - name: Install calico pod network
    become: false
    command: kubectl apply -f "{{ DATA_PATH }}"calico.yaml

  - name: Install dashboard
    become: false
    shell:
        kubectl apply 
        -f "{{ DATA_PATH }}"dashboard.yaml 
        -f "{{ DATA_PATH }}"dashboard-admin.yaml 
        -f "{{ DATA_PATH }}"dashboard-read-only.yaml

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: shared_data

  - name: Copy join command to shared data
    local_action: copy content="{{ shared_data.stdout_lines[0] }}" dest="./shared-data"
      
  - name: Copy admin.conf to shared data
    local_action: copy content="/etc/kubernetes/admin.conf" dest="./shared-data"

  - name: Setup auto completion bash
    shell: |
      echo "source <(kubectl completion bash)" >>~/.bashrc
      kubectl completion bash >/etc/bash_completion.d/kubectl
      source /usr/share/bash-completion/bash_completion
    become: yes
    become_user: vagrant

#  handlers:
#    - name: docker status
#      service: name=docker state=started