---
- hosts: master-node #nfs-server
  vars:
    DATA_PATH: /opt/kubernetes/examples/
  become: true
  tasks:

  - name: Copy YAML Files
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: '/opt/kubernetes/examples/', dest: "{{ DATA_PATH }}" }
