---
- hosts: master-node
  vars:
    DATA_PATH: /opt/kubernetes/
  become: true
  tasks:

  - name: Copy YAML Files
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: '/opt/kubernetes/examples/', dest: "{{ DATA_PATH }}" }
      - { src: '/opt/kubernetes/examples/admin', dest: "{{ DATA_PATH }}" }

#  - name: Install Calico Pod Network
#    command: kubectl apply -f "{{ DATA_PATH }}admin/"calico.yaml

#  - name: Copy YAML Files
#    copy: src={{ item.src }} dest={{ item.dest }}
#    with_items:
#      - { src: 'ingress-nginx.yaml', dest: "{{ DATA_PATH }}" }

#  - name: Install Nginx Ingress
#    shell:
#        kubectl apply
#        -f "{{ DATA_PATH }}"ingress-nginx.yaml

#  - name: 1 minute wait for initialization
#    pause:
#      minutes: 1

#  - name: Install Prometheus & Grafana
#    shell: |
#      kubectl create ns monitoring
#      helm install prometheus stable/prometheus-operator --namespace monitoring

#  - name: Copy YAML files
#    copy: src={{ item.src }} dest={{ item.dest }}
#    with_items:
#      - { src: 'calico.yaml', dest: "{{ DATA_PATH }}" }
#      - { src: 'dashboard.yaml', dest: "{{ DATA_PATH }}" }
#      - { src: 'dashboard-admin.yaml', dest: "{{ DATA_PATH }}" }
#      - { src: 'dashboard-read-only.yaml', dest: "{{ DATA_PATH }}" }
#      - { src: 'dashboard-ingress.yaml', dest: "{{ DATA_PATH }}" }
#      - { src: 'ingress-nginx.yaml', dest: "{{ DATA_PATH }}" }



#  - name: 1 minute wait for initialization
#    pause:
#      minutes: 1

#  - name: Install Dashboard
#    shell:
#        kubectl apply
#        -f "{{ DATA_PATH }}"dashboard.yaml
#        -f "{{ DATA_PATH }}"dashboard-admin.yaml
#        -f "{{ DATA_PATH }}"dashboard-read-only.yaml