---
- hosts: master-node
  vars:
    MASTER_IP: 192.168.10.11
    POD_CIDR: 192.168.50.0/24
    DATA_PATH: /opt/kubernetes/
    NON_ROOT_USER: vagrant
  become: true
  tasks:
 
  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="{{ MASTER_IP }}" --apiserver-cert-extra-sans="{{ MASTER_IP }}"  --node-name k8s-master --pod-network-cidr={{ POD_CIDR }}

  - name: Configure for non-root
    shell: |
      sudo rm -rf $HOME/.kube
      mkdir -p $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config
    become: yes
    become_user: "{{ NON_ROOT_USER }}"

  - name: Configure for root
    shell: |
      sudo rm -rf $HOME/.kube
      mkdir -p $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Copy yaml files
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: 'calico.yaml', dest: "{{ DATA_PATH }}" }
      - { src: 'dashboard.yaml', dest: "{{ DATA_PATH }}" }
      - { src: 'dashboard-admin.yaml', dest: "{{ DATA_PATH }}" }
      - { src: 'dashboard-read-only.yaml', dest: "{{ DATA_PATH }}" }

  - name: Install calico pod network
    command: kubectl apply -f "{{ DATA_PATH }}"calico.yaml

  - name: Install dashboard
    shell:
        kubectl apply 
        -f "{{ DATA_PATH }}"dashboard.yaml 
        -f "{{ DATA_PATH }}"dashboard-admin.yaml 
        -f "{{ DATA_PATH }}"dashboard-read-only.yaml

  - name: Generate shared for join command
    command: kubeadm token create --print-join-command
    register: shared_data1
    
  - name: Copy join command to shared data
    local_action: copy content="{{ shared_data1.stdout_lines[0] }}" dest="./shared-data-command"
    
  - name: Generate shared for admin.con
    command: cat /etc/kubernetes/admin.conf
    register: shared_data2
    
  - name: Copy admin.conf to shared data
    local_action: copy content="{{ shared_data2 }}" dest="./shared-data-conf"
    
  - name: Auto completion for non-root user
    shell: |
      echo "source <(kubectl completion bash)" >>~/.bashrc
      sudo kubectl completion bash >/etc/bash_completion.d/kubectl
    become_user: "{{ NON_ROOT_USER }}"

  - name: Auto completion for root user
    shell: |
      echo "source <(kubectl completion bash)" >>~/.bashrc
      sudo kubectl completion bash >/etc/bash_completion.d/kubectl

  - name: Setup auto completion
    shell: source $HOME/.bashrc && source /usr/share/bash-completion/bash_completion
    args:
      executable: /bin/bash

#  handlers:
#    - name: docker status
#      service: name=docker state=started