---
- hosts: all
  vars:
    master_node_ip: 192.168.10.11
    pod_network_cidr: 192.168.50.0/24
  become: true
  tasks:
  
#  - name: Initialize the Kubernetes cluster using kubeadm
#    command: kubeadm init --apiserver-advertise-address="{{ master_node_ip }}" --apiserver-cert-extra-sans="{{ master_node_ip }}"  --node-name k8s-master --pod-network-cidr={{ pod_network_cidr }}

  - name: Setup kubeconfig for vagrant user
    shell: |
      mkdir -p /home/vagrant/.kube
      cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
      chown vagrant:vagrant /home/vagrant/.kube/config

  - name: Copy yaml files
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: 'calico.yaml', dest: '/opt/kubernetes/' }
      - { src: 'dashboard.yaml', dest: '/opt/kubernetes/' }
      - { src: 'dashboard-admin.yaml', dest: '/opt/kubernetes/' }
      - { src: 'dashboard-read-only.yaml', dest: '/opt/kubernetes/' }

  - name: Install calico pod network
    become: false
    command: kubectl apply -f calico.yaml

  - name: Install dashboard
    become: false
    command: |
      - kubectl apply -f dashboard.yaml
      - kubectl apply -f dashboard-admin.yaml
      - kubectl apply -f dashboard-read-only.yaml