---
- hosts: worker-node
  become: true
  tasks:

  - name: Get join command from master
    copy: src=shared-data1 dest=/tmp/shared-data.sh mode=0777

  - name: Join the node to cluster
    command: sh /tmp/shared-data.sh

  - name: Get /etc/kubernetes/admin.conf from master
    copy: src=shared-data2 dest=/etc/kubernetes/admin.conf mode=0777

  - name: Initialize kubectl command
    shell: |
      sudo rm -rf $HOME/.kube
      mkdir -p $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config
    become: yes
    become_user: vagrant

  - name: Setup auto completion - step 1
    shell: |
      echo "source <(kubectl completion bash)" >>~/.bashrc
      sudo kubectl completion bash >/etc/bash_completion.d/kubectl

  - name: Setup auto completion - step 2
    shell: source $HOME/.bashrc && source /usr/share/bash-completion/bash_completion
    args:
      executable: /bin/bash