---
- hosts: master-node
  vars:    
    MASTER_IP: 192.168.10.11
    POD_CIDR: 10.244.0.0/16
    NON_ROOT_USER: vagrant
    DATA_PATH: /opt/kubernetes/examples
  become: true
  tasks:

  - name: Initialize Kubernetes Cluster using Kubeadm
    command: kubeadm init --apiserver-advertise-address="{{ MASTER_IP }}" --apiserver-cert-extra-sans="{{ MASTER_IP }}" --node-name k8s-master --pod-network-cidr={{ POD_CIDR }}

  - name: Configure for non-root
    shell: |
      sudo rm -rf $HOME/.kube
      mkdir -p $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config
    become: yes
    become_user: "{{ NON_ROOT_USER }}"

  - name: Configure for root
    shell: |
      sudo rm -rf $HOME/.kube
      mkdir -p $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Install Helm
    shell: |
      curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
      sudo apt-get install apt-transport-https --yes
      echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
      sudo apt-get update
      sudo apt-get install helm

  - name: Generate Shared Data for Join Command
    command: kubeadm token create --print-join-command
    register: shared_data1

  - name: Copy Join Command to Shared Data
    local_action: copy content="{{ shared_data1.stdout_lines[0] }}" dest="./shared-data-command"

  - name: Auto Completion for non-root user
    shell: |
      sudo echo "source <(kubectl completion bash)" >>~/.bashrc
    become_user: "{{ NON_ROOT_USER }}"

  - name: Auto Completion for root user
    shell: |
      sudo echo "source <(kubectl completion bash)" >>~/.bashrc
      sudo kubectl completion bash >/etc/bash_completion.d/kubectl

  - name: Setup Auto Completion
    shell: |
      source $HOME/.bashrc && source /usr/share/bash-completion/bash_completion
    args:
      executable: /bin/bash

  - name: Copy admin.conf to hostmachine
    ansible.builtin.fetch:
      src: /etc/kubernetes/admin.conf
      dest: /tmp/admin.conf
      flat: yes
    become: yes
    become_user: "root"

  - name: Copy YAML Files
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: '/opt/kubernetes/examples/', dest: "{{ DATA_PATH }}" }

  - name: Install Calico Pod Network
    command: kubectl apply -f "{{ DATA_PATH }}/admin/calico.yaml"

  - name: 3 minute wait for initialization
    pause:
      minutes: 3

  - name: Install Nginx Ingress
    shell: 
        kubectl apply
        -f "{{ DATA_PATH }}/admin/ingress-nginx.yaml"

  - name: Install Dashboard
    shell:
        kubectl apply
        -f "{{ DATA_PATH }}/admin/"dashboard.yaml
        -f "{{ DATA_PATH }}/admin/"dashboard-admin.yaml
        -f "{{ DATA_PATH }}/admin/"dashboard-read-only.yaml