---
- hosts: master-node,worker-node
  vars:
    NON_ROOT_USER: vagrant
  become: true
  tasks:
  - name: Update /etc/resolv.conf for Corporate Network
    ansible.builtin.lineinfile:
      path: /etc/resolv.conf
      line: nameserver 8.8.8.8

  - name: Update Packages
    apt:
      update_cache: yes

  - name: Install Packages
    apt:
      state: present
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - bash-completion
        - gnupg2
        - nfs-common

  - name: Disable Swap Space
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Docker apt signing key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    retries: 3
          
  - name: Docker apt reposiotry
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable
    retries: 3

  - name: Install Docker
    apt:
      state: present
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io

  - name: Add non-root User to Docker Group
    user:
      name: "{{ NON_ROOT_USER }}"
      group: docker

  - name: Kubernetes apt signing key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
    retries: 3

  - name: Kubernetes apt repository
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list
    retries: 3

  - name: Install Kubernetes
    apt: 
      state: present
      update_cache: yes
      name: 
        - kubelet 
        - kubeadm 
        - kubectl