---
- hosts: master-node
  vars:
    MASTER_IP: 192.168.10.11
    POD_CIDR: 192.168.50.0/24
    DATA_PATH: /opt/kubernetes/
  become: true
  tasks:
  
  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="{{ MASTER_IP }}" --apiserver-cert-extra-sans="{{ MASTER_IP }}"  --node-name k8s-master --pod-network-cidr={{ POD_CIDR }}

  - name: Setup kubeconfig for vagrant user
    shell: |
      mkdir -p /home/vagrant/.kube
      cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
      chown vagrant:vagrant /home/vagrant/.kube/config

  - name: Copy yaml files
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: 'calico.yaml', dest: "{{ DATA_PATH }}" }
      - { src: 'dashboard.yaml', dest: "{{ DATA_PATH }}" }
      - { src: 'dashboard-admin.yaml', dest: "{{ DATA_PATH }}" }
      - { src: 'dashboard-read-only.yaml', dest: "{{ DATA_PATH }}" }

  - name: Install calico pod network
    become: false
    command: kubectl apply -f "{{ DATA_PATH }}"calico.yaml

  - name: Install dashboard
    become: false
    command: |
      kubectl apply 
      -f "{{ DATA_PATH }}"dashboard.yaml
      -f "{{ DATA_PATH }}"dashboard-admin.yaml
      -f "{{ DATA_PATH }}"dashboard-read-only.yaml