---
- hosts: nfs-server
  vars:
    NFS_SHARE: /mnt/k8s-data
    NODE_CIDR: 192.168.10.0/24
    DATA_PATH: /opt/kubernetes/examples/
  become: true
  tasks:

  - name: Update Packages
    apt:
      update_cache: yes

  - name: Install Package NFS-Server
    apt:
      state: present
      name:
        - nfs-kernel-server

  - name: Create NFS Export Directory
    shell: |
      mkdir -p "{{ NFS_SHARE }}"
      chown -R nobody:nogroup "{{ NFS_SHARE }}"/
      chmod 777 "{{ NFS_SHARE }}"/

  - name: Grant NFS Share Access to Client Systems
    ansible.builtin.lineinfile:
      path: /etc/exports
      line: '{{ NFS_SHARE }} {{ NODE_CIDR }}(rw,sync,no_subtree_check)'
      create: yes

  - name: Export NFS Share Directory
    shell: |
      exportfs -a
      systemctl restart nfs-kernel-server

  - name: Allow NFS Access through Firewall
    shell: |
      ufw allow from {{ NODE_CIDR }} to any port nfs

  - name: Copy YAML Files
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: '/opt/kubernetes/examples/', dest: "{{ DATA_PATH }}" }

  - name: Install NFS Provisioner
    shell:
        kubectl apply
        -f "{{ DATA_PATH }}"nfs-namespace.yaml
        -f "{{ DATA_PATH }}"nfs-class.yaml
        -f "{{ DATA_PATH }}"nfs-rbac.yaml
        -f "{{ DATA_PATH }}"nfs-deployment.yaml