---
- hosts: all
  become: true
  tasks:
  - name: Update /etc/resolv.conf for corporate network
    ansible.builtin.lineinfile:
      path: /etc/resolv.conf
      line: nameserver 8.8.8.8

  - name: Update packages
    command: "{{ item }}"
    with_items:
    #- rm -vf /var/lib/apt/lists/*
    - apt update

  - name: Install Packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg2
        - nfs-common

  - name: Disable swap space
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Docker apt signing key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    #command: "{{ item }}"
    #with_items:
    #- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key --keyring /etc/apt/trusted.gpg.d/docker.gpg add -
    #- add-apt-repository deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable
    #- apt update
    retries: 3
          
  - name: Docker apt reposiotry
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable
    retries: 3

  - name: Install docker
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    notify:
      - docker version

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  - name: Kubernetes apt signing key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
    retries: 3

  - name: Kubernetes apt repository
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list
    retries: 3

  - name: Install Kubernetes
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl
    notify:
      - kubectl version

  - name: Print installed version
    shell: "{{ item }}"
    with_items:
      - kubectl version --short
      - docker version
    ignore_errors: yes