apiVersion: v1
kind: Service
metadata:
  name: zabbix-web-svc
  namespace: zabbix-devops
  labels:
    app: zabbix-web
    tier: frontend
spec:
  selector:
    app: zabbix-web-dep
    tier: frontend
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32070