apiVersion: v1
kind: Service
metadata:
  name: zabbix-postgres-svc
  namespace: zabbix-devops
spec:
  selector:
    app: zabbix-postgres-sts
    tier: db
  type: ClusterIP
  ports:
    - name: http
      port: 5432
      targetPort: 5432