apiVersion: v1
kind: Service
metadata:
  name: zabbix-server-svc
  labels:
    app: zabbix-server
    tier: server
  namespace: zabbix-devops
spec:
  selector:
    app: zabbix-server
    tier: server
  ports:
  - port: 10051
    targetPort: 10051
    name: zabbix-trapper
  - port: 162
    targetPort: 1162
    protocol: UDP
    name: snmp-trap
#  externalIPs:
#  - <Specify external IP here>