apiVersion: v1
kind: Service
metadata:
  name: zabbix-java-gateway-svc
  labels:
    app: zabbix-java-gateway
    tier: backend
  namespace: zabbix-devops
spec:
  selector:
    app: zabbix-java-gateway
    tier: backend
  ports:
  - port: 10052
    targetPort: 10052
    name: zabbix-jmx