apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-postgres-sts
  namespace: zabbix-devops
  labels:
    app: zabbix-postgres-sts
    tier: db
spec:
  serviceName: zabbix-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-postgres-sts
      tier: db
  template:
    metadata:
      labels:
        app: zabbix-postgres-sts
        tier: db
    spec:
      containers:
      - name: postgres
        image: postgres:12.6
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: zabbix-postgres-configmap
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-postgres-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: zabbix-postgres-pvc