apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-server-pvc
  namespace: zabbix-devops
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi