apiVersion: apps/v1
kind: Deployment #DaemonSet
metadata:
  name: zabbix-agent-dep
  labels:
    app: zabbix-server
    tier: agent
  namespace: zabbix-devops
spec:
  selector:
   matchLabels:
    app: zabbix-server
    tier: agent
  template:
    metadata:
      labels:
        app: zabbix-server
        tier: agent
    spec:
      containers:
        - name: zabbix-agent
          image: zabbix/zabbix-agent:alpine-5.2-latest
          imagePullPolicy: Always
          resources:
           limits:
            cpu: 100m
            memory: 54Mi
           requests:
            cpu: 100m
            memory: 54Mi
          ports:
          - containerPort: 10050
            name: zabbix-agent
          env:
          - name: ZBX_SERVER_HOST
            value: zabbix-server-svc.zabbix-devops.svc.cluster.local #"zabbix-server"
          securityContext:
            privileged: true