apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-java-gateway-dep
  namespace: zabbix-devops
  labels:
    app: zabbix-java-gateway
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-java-gateway
      tier: backend
  template:
    metadata:
      labels:
        app: zabbix-java-gateway
        tier: backend
    spec:
      containers:
        - name: zabbix-java-gateway
          image: zabbix/zabbix-java-gateway:alpine-5.2-latest
          imagePullPolicy: Always
          resources: 
#            requests:
#              cpu: "500m"
#              memory: "0.5Gi"
#            limits:
#              cpu: "1000m"
#              memory: "1Gi"
          ports:
          - containerPort: 10052
            protocol: TCP
            name: zabbix-jmx
          env:
          - name: ZBX_TIMEOUT
            value: "5"