apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-dep
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:3.29.0
          env:
          - name: MAX_HEAP
            value: "4g"
          - name: MIN_HEAP
            value: "4g"
          resources: 
            requests:
              cpu: "500m"
              memory: "1000Mi"
            limits:
              cpu: "1000m"
              memory: "2000Mi"
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc