apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: nexus-pvc-nfs
 namespace: devops-nexus
spec:
 storageClassName: nfs-storageclass
 accessModes:
 - ReadWriteMany
 resources:
  requests:
   storage: 3Gi
