apiVersion: v1
kind: Service
metadata:
  name: ldap-svc
  namespace: devops #ldap
spec:
  selector:
    app: ldap
  ports:
    - port: 389
---
apiVersion: v1
kind: Service
metadata:
  name: ldap-nodeport-svc
  namespace: devops #ldap
spec:
  type: NodePort
  selector:
    app: ldap
  ports:
    - port: 389
      targetPort: 389
      nodePort: 32050