apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-php-admin-dep
  namespace: devops #ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap-php-admin
  template:
    metadata:
      labels:
        app: ldap-php-admin
    spec:
      containers:
        - name: phpldapadmin
          image: osixia/phpldapadmin:0.7.1
          env:
            - name: PHPLDAPADMIN_HTTPS
              value: "false"
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: "ldap-svc"
          ports:
            - containerPort: 80