apiVersion: v1
kind: Service
metadata:
  name: ldap-php-admin-svc
  namespace: devops #ldap
spec:
  selector:
    app: ldap-php-admin
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 32060