apiVersion: v1
kind: Service
metadata:
  name: openldap-svc
  namespace: ldap
spec:
  selector:
    app: openldap
  type: NodePort #ClusterIP
  ports:
    - name: tcp-ldap
      port: 1389
      targetPort: tcp-ldap
      nodePort: 32050