apiVersion: v1
kind: Service
metadata:
  name: openldap-svc
  namespace: openldap
spec:
  selector:
    app: openldap
  type: NodePort
  ports:
  - name: http
    port: 1389
    targetPort: 1389
    nodePort: 32060