apiVersion: v1
kind: Service
metadata:
  name: ldap-svc
  namespace: ldap
spec:
  selector:
    app: ldap
  type: NodePort
  ports:
  - name: http
    port: 1389
    targetPort: 1389
    nodePort: 32060