apiVersion: v1
kind: Service
metadata:
  name: ldap-ui-svc
  namespace: devops #ldap
spec:
  selector:
    app: phpldapadmin
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
    nodePort: 32060